# Accelerate configuration for multi-GPU feature extraction
# Usage: accelerate launch --config_file accelerate_config.yaml utils/feature_extract_accelerate.py [args...]

compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU # MULTI_GPU NO
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: '0,1,2,3,4,5,6,7' # all or specify like: '0,1,2,3,4,5,6,7'
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 8  # Number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
dynamo_backend: 'no'
